# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-SMIME
version:      0.08
version_from: SMIME.pl
installdirs:  site
requires:
    Test::Exception:               0
    Test::More:                    0
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
